---

- name: Add SaltStack PPA
  apt_repository:
    repo: "ppa:{{ salt_repo }}"
    state: present

- name: Install packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  with_items: "{{ packages }}"

- name: Update {{ conf_file.location }}
  template:
    src: "{{ conf_file.template }}"
    dest: "{{ conf_file.location }}"
    mode: 0644
  notify: restart salt


- name: Accept keys
  command: "salt-key -A"
  when: role == "master"
